### ISSUE TITLE
Gas Circulation System

### ISSUE THREAD

**Issue by mrtegri** [DavidWenzler/reAM250#6]
Hi @DavidWenzler ,

I did not fully understand the reason for this connection between vacuum and pressure in the gas circulation system. Can you provide information on this subject? Also, what are the differences in the system you use different from the Becker VASF 2.5 series. 

BR
![gss](https://github.com/user-attachments/assets/a0e6d1c0-4bdd-433d-83d2-240069e0bea5)

**Comment by DavidWenzler** [comment]
Thank you for pointing this out. This is an error in the CAD model. The connection short-circuits the gas system. We fixed this issue a while ago but unfortunately did not update it in the model. We will provide an updated model and BoM fixing this problem within the next week. The vacuum pump we are using is a Pfeiffer Vaccuum DUO 35. You find all the information on the pump here: https://www.pfeiffer-vacuum.com/global/de/shop/products/PK_D45_028_E

**Comment by SquishyBoiFrog** [comment]
I was wondering is this apart of the Gas or the vacuum system? Nothing seems to be piped to this area.
<img width="662" alt="image" src="https://github.com/user-attachments/assets/fcd31815-67c1-46de-bf17-0cfdea741fbf" />
Here's a better photo of the troubled area in Blue.
![image](https://github.com/user-attachments/assets/d40b4902-56b7-4d50-ae4f-9109408d6b24)

**Comment by DavidWenzler** [comment]
Hi, this is the outlet for the cables connected to the motors and sensors in the chamber. Unfortunately, we don’t have a CAD model of the outlet. We used a standard cable gland and we will fillt it with resin to seal it. We will upload some photos of the current state of the machine to the homepage, where the outlet will be visible.

**Comment by mrtegri** [comment]
Hello,

Did you update the model?

It still shows the old version.

**Comment by DavidWenzler** [comment]
Hi, we updated the CAD files today. Check out the new version: https://davidwenzler.github.io/reAM250/cad/

**Comment by cocmo1024** [comment]
I see that the CAD short-circuit was corrected and the updated model was posted. For future builders, I would still document this subsystem as a P&ID plus an operating state machine rather than only as a component comparison:

purge -> evacuate -> inert backfill -> recirculate -> controlled vent / fault.

The drawing and controls table should make the following explicit:

- check-valve direction, relief path, blower/pump isolation, and valve fail states;
- which transitions are permitted by chamber pressure;
- chamber O2, dew point, circulation flow, and differential pressure across the filter;
- alarm and safe-state behavior for low flow, high filter ΔP, rising O2, or lost sensor signal; and
- how the cable gland and other penetrations are leak-checked after maintenance.

For material changes, the service procedure should also define conductive-dust grounding and a cleaning/verification step to prevent cross-contamination, especially between copper and reactive titanium feedstock. If vacuum and recirculation share any pipework, backflow and pump-oil/particle migration belong in the interlock review as well.

We use the same atmosphere and process-route questions when screening [copper LPBF capability](https://copper3dp.com/capabilities/). Disclosure: I work with COPPER 3DP / Como Precision.
